### ISSUE TITLE
Website css gone?

### ISSUE THREAD

**Issue by jonas-xyz** [opera7133/tella#110]
I'm new to Hugo so please forgive me. I tried to add `| safeURL` to config.toml so that I can use `"url" = "tel:133742069" `as url for one of the `menu.main `things. After I did that my whole website broke. Even now after I removed it everything is broken and doesn't show properly at all. When I go to themes/tella/assets/css/main.css the `@tailwind` imports are underlined and it says "Unknown at rule @tailwind" (I'm using VSCode). So I think I somehow broke it and now everything's not working anymore. Any idea on how to fix it?

**Comment by opera7133** [comment]
I tried it in my environment. I was able to change it without any problems.
Perhaps the CSS is not building properly, or somehow the tailwind command is not running in `npm run start`, or some other issue.
In most cases, deleting the resources folder or stopping preview and running it again should solve the problem.
You can check the CSS output with `npm run watch:tw`.

**Comment by jonas-xyz** [comment]
`npm run watch:tw `gives this output:

```
tella@0.0.1 watch:tw
> tailwindcss -i ./themes/tella/assets/css/main.css -o ./themes/tella/assets/css/style.css --watch
```
problem is still there. I don't know what happened. I really only added `| safeURL` to config.toml

**Comment by opera7133** [comment]
What does your config.toml look like? That may be the problem.

**Comment by jonas-xyz** [comment]
[config.txt](https://github.com/opera7133/tella/files/9375108/config.txt)

**Comment by opera7133** [comment]
I went through the config.toml and actually tested it and it displayed correctly.
I thought you had made a mistake where you put the safeURL...
The only sure solution is to re-install the theme or remove node_modules and re-install it again.
Deleting assets/css/style.css and re-generating it may also help.

**Comment by jonas-xyz** [comment]
okay, thank you very much. I'm gonna reinstall and see if it works.

**Comment by jonas-xyz** [comment]
The problem fixed itself. It now works again. Maybe there was a problem with the browser cache or something (even though I restarted my PC).
